services:
  whisper-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./projects:/app/projects
      - ./stages:/app/stages
      - ./models:/app/models
      - ./templates:/app/templates
      - ./static:/app/static
      - ./app.py:/app/app.py
      - ./transcript_database_client.py:/app/transcript_database_client.py
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - CUDA_CACHE_DISABLE=0
      - CUDA_LAUNCH_BLOCKING=0
      # - TRANSCRIPT_DB_URL=${TRANSCRIPT_DB_URL:-http://host.docker.internal:5001}  # Local testing
      - TRANSCRIPT_DB_URL=${TRANSCRIPT_DB_URL:-https://mycomments.duckdns.org:5001}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    restart: unless-stopped